### ISSUE TITLE
Quota exceeded for resources: ["router"].", "type": "OverQuota"

### ISSUE THREAD

**Issue by maxim-ge** [selectel/terraform-examples#3]
Your example `server_remote_root_disk` works nice for one server. 

But I need at least  three servers. Ovbious modification https://pastebin.com/tM0gdDY2 does not work since it creates a router for each server and soon internal quota for routers (2 allowed) excceeds. I managed to modify your scripts to get three servers - it creates nat first and then creates servers - but I think there should be an "out of the box" way. May be I did not get the situation and it is possible?

**Comment by dkder3k** [comment]
In #7 I've added a simple example that creates several servers in the same network.
@maxim-ge as you've noticed each server module in this example repo creates separate network. So if you want to create servers with different configurations you should do it as in "several_servers_one_network" example: create network (via "nat" module or somehow else), then use this network to configure compute instances ports.
