### ISSUE TITLE
Нет примера для HTTPS listener

### ISSUE THREAD

**Issue by horeca2** [selectel/terraform-examples#35]
Здесь указано что будет создан балансировщик с HTTPS 

https://github.com/selectel/terraform-examples/blob/8fd9ec36b7f6fbbcbf83a4fc46fa52a3be55c4bd/examples/vpc/several_servers_and_loadbalancers_without_project/main.tf#L39

но в vars.tf 
https://github.com/selectel/terraform-examples/blob/8fd9ec36b7f6fbbcbf83a4fc46fa52a3be55c4bd/examples/vpc/several_servers_and_loadbalancers_without_project/vars.tf#L36

вы указываете протокол HTTP

Я так и не разобрался как добавить SSL к HTTPS слушателю

**Comment by horeca2** [comment]
А тут https://github.com/selectel/terraform-examples/pull/33 вы по какой то причине удалили пример с HTTPS.
Это пока не работает?

**Comment by Koodt** [comment]
Привет! Мы временно убрали HTTPS из примеров, в связи с тем, что у нас менялся сервис хранения сертификатов.
На данный момент мы используем свой сервис секретов.
Добавить HTTPS правило можно, если вы добавите сертификат в этот сервис и используете его UUID в качестве ссылки на контейнер.
Этот пример мы добавим в ближайшее время.

**Comment by horeca2** [comment]
Я не нашел поддержки в terraform вашего нового менеджера секретов. Означает ли это, что я должен добавлять сертификат вручную через панель управления? Если да, то я не найду в панели управления UUID сертификата

**Comment by Koodt** [comment]
Мы добавили в панель отображение UUID сертификатов.
Его можно использовать в качестве ссылки на контейнер при добавлении HTTPS правила.
Сами сертификаты можно добавлять через панель и API менеджера секретов.
Информацию о менеджере секретов и его API можно найти в наших базе знаний и документации к API.
