### ISSUE TITLE
Example cluster_one_nodegroup_with_net_infra does not work properly

### ISSUE THREAD

**Issue by gyrter** [selectel/terraform-examples#40]
Hello. Your examples are perfect, but i found little problem with `cluster_one_nodegroup_with_net_infra`

It did not create node group if you specify keypair
```
╷
│ Error: error creating nodegroup: unable to find new nodegroup by ID after creating
│ 
│   with module.kubernetes_front_nodegroup.selectel_mks_nodegroup_v1.nodegroup_1,
│   on terraform-examples/modules/mks/nodegroup/main.tf line 1, in resource "selectel_mks_nodegroup_v1" "nodegroup_1":
│    1: resource "selectel_mks_nodegroup_v1" "nodegroup_1" {
│ 
╵
╷
│ Error: error creating nodegroup: unable to find new nodegroup by ID after creating
│ 
│   with module.kubernetes_system_nodegroup.selectel_mks_nodegroup_v1.nodegroup_1,
│   on terraform-examples/modules/mks/nodegroup/main.tf line 1, in resource "selectel_mks_nodegroup_v1" "nodegroup_1":
│    1: resource "selectel_mks_nodegroup_v1" "nodegroup_1" {
│ 
╵
╷
│ Error: error creating nodegroup: unable to find new nodegroup by ID after creating
│ 
│   with module.kubernetes_nodegroup.selectel_mks_nodegroup_v1.nodegroup_1,
│   on terraform-examples/modules/mks/nodegroup/main.tf line 1, in resource "selectel_mks_nodegroup_v1" "nodegroup_1":
│    1: resource "selectel_mks_nodegroup_v1" "nodegroup_1" {
│ 
```

**Comment by syedammar111** [comment]
Even if you dont specify keypair, it is giving me the same issue. Did you get a solution to this?

**Comment by TawR1024** [comment]
@syedammar111 Hey, which keypair do you use, domain or project ? Can you give an example of your manifest ?

**Comment by syedammar111** [comment]
I am not even using a keypair and still receiving this error: 
 Error: error creating nodegroup: unable to find new nodegroup by ID after creating

**Comment by TawR1024** [comment]
> 
Which terraform-provider do you use? 
Current stable version is v3.9.1, I have tried to create cluster without keypair and it works properly. Please show your terraform manifest.

my main.tf
```
...
module "kubernetes_nodegroup" {
  source = "../../../modules/mks/nodegroup"
  cluster_id        = module.kubernetes_cluster.cluster_id
  project_id        = module.kubernetes_cluster.project_id
  region            = module.kubernetes_cluster.region
  availability_zone = var.availability_zone
  nodes_count       = var.nodes_count
  keypair_name      = var.keypair_name
  affinity_policy   = var.affinity_policy
  cpus              = var.cpus
  ram_mb            = var.ram_mb
  volume_gb         = var.volume_gb
  volume_type       = var.volume_type
  labels            = var.labels
  taints            = var.taints 
}
```
my vars.tf
```
...
variable "keypair_name" {
  default = ""
}
```

Also, keypair is [optional](https://github.com/selectel/terraform-provider-selectel/blob/6d8de49c1e39c3cf8f896d6db99e029ac361d62a/selectel/resource_selectel_mks_nodegroup_v1.go#L68), so you can skip it.

**Comment by gyrter** [comment]
>Also, keypair is optional, so you can skip it.

But I want to connect to nodes over ssh. It can help with some tasks.

**Comment by Koodt** [comment]
```
> │ Error: error creating nodegroup: unable to find new nodegroup by ID after creating
```

Hi! Looks like quota was exceeded. Can you send ticket to our support team, please?

**Comment by Koodt** [comment]
> > Also, keypair is optional, so you can skip it.
> 
> But I want to connect to nodes over ssh. It can help with some tasks.

Hi! This option will be deprecated in next MKS API release. Won't fix.
