### ISSUE TITLE
не проходят валидацию проекты из examples

### ISSUE THREAD

**Issue by burundukoff** [selectel/terraform-examples#53]
при попытке сделать validate на проекты папки :
── vpc
│       ├── preemptible_server
│       ├── preemptible_server_with_gpu"
и возможно другие получаю ошибку:
Error: Unsupported argument
│ 
│   on ../../../modules/vpc/project_with_user/main.tf line 8, in module "user":
│    8:   user_name     = var.project_user_name
│ 
│ An argument named "user_name" is not expected here.

При этом изменений еще не вносилось

**Comment by TruePack** [comment]
Спасибо! Поправили примеры, теперь должно заработать.

**Comment by burundukoff** [comment]
Буду очень благодарен, если скажите в чем был баг, так сказать в целях повышения собственной образованности.
